# -*- coding: utf-8 -*-
"""MIS_Course.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RewrTvz0aTEZTgJaJpQ15O9RqpmDRlCR
"""

print("Hello World!!")

